CREATE DATABASE IF NOT EXISTS LIMS;
USE LIMS;

CREATE TABLE IF NOT EXISTS Attribute (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(99) NOT NULL,
    unit VARCHAR(6),
    placeholder VARCHAR(30) NOT NULL,
    regex VARCHAR(199) NOT NULL,
    actived BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS State (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(199) NOT NULL,
    actived BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Sample (
    id INT(7) NOT NULL PRIMARY KEY,
    barcode VARCHAR(11) NOT NULL,
    state INT NOT NULL REFERENCES State(id)
);

CREATE TABLE IF NOT EXISTS Operator (
    id INT(5) NOT NULL PRIMARY KEY,
    name VARCHAR(199) NOT NULL,
    type BOOLEAN DEFAULT 0,
    actived BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Test (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(199) NOT NULL,
    samplesLength INT NOT NULL,
    require_State INT NULL REFERENCES State(id),
    initial_State INT NOT NULL REFERENCES State(id),
    actived BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SampleValue(
    sample_Id INT NOT NULL REFERENCES Sample(id),
    test_Id INT NOT NULL REFERENCES Test(id),
    attribute_Id INT NOT NULL REFERENCES Attribute(id),
    value VARCHAR(199) NOT NULL
);

CREATE TABLE IF NOT EXISTS TestAttributes(
    test_Id INT NOT NULL REFERENCES Test(id),
    attribute_Id INT NOT NULL REFERENCES Attribute(id)
);

CREATE TABLE IF NOT EXISTS TestStatus(
    test_Id INT NOT NULL REFERENCES Test(id),
    result_State INT NOT NULL REFERENCES State(id)
);

CREATE TABLE IF NOT EXISTS Log(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    operator_Id INT NOT NULL REFERENCES Operator(id),
    sample_Id INT NOT NULL REFERENCES Sample(id),
    test_Id INT NOT NULL REFERENCES Test(id),
    status_Id INT NOT NULL REFERENCES State(id),
    onCreated DATETIME NOT NULL
);